version: '3.1'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    container_name: wolo-app-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - dbpostgresql
    restart: on-failure
  dbpostgresql:
    image: postgres
    container_name: dbpostgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: on-failure
