version: '3.1'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    container_name: wolo-app-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgresql:5432/mydb2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - dbpostgresql
    restart: unless-stopped
  dbpostgresql:
    image: postgres
    container_name: dbpostgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb2
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped


