
FROM gradle:latest

# Utwórz katalog aplikacji
WORKDIR /wolo-app-api

# Skopiuj pliki aplikacji do kontenera
COPY . /wolo-app-api

# Otwórz port, na którym działa aplikacja Spring Boot
EXPOSE 8080

# Uruchom aplikację
CMD ["gradle", "bootRun", "-x", "test"]
