version: '3.1'
services:
  backend:
    container_name: wolo-app-api
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - dbpostgresql
    restart: on-failure
  dbpostgresql:
    container_name: dbpostgresql
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    restart: on-failure
volumes:
  db-data: