--liquibase formatted sql

--changeset woloapp:4
INSERT INTO address (street, home_num, district_id) VALUES
                                                                        ('Wajdeloty ', '25/1', 2),
                                                                        ('Aldony ', '2A/4', 2),
                                                                        ('Falista', '8', 2),
                                                                        ('Kręta', '67', 2),
                                                                        ('Aleja Grunwaldzka', '82', 2),
                                                                        ('3 Maja', '9', 3),
                                                                        ('Dobra', '8', 3),
                                                                        ('Jaglana', '6E', 3),
                                                                        ('Kubusia Puchatka', '4', 4),
                                                                        ('Piastowska', '90B', 4),
                                                                        ('Poczty Gdańskiej ', '7', 4),
                                                                        ('Marii Skłodowskie-Curie', '3b', 5),
                                                                        ('Wronia', '31', 5),
                                                                        ('Daniela Chodowieckiego', '7', 5),
                                                                        ('Dworcowa', '7', 7),
                                                                        ('Koralowa', '2', 7),
                                                                        ('Świętopełka', '50', 9),
                                                                        ('Anastazego Wika-Czarnowskiego', '1A', 9),
                                                                        ('gen. Bora-Komorowskiego ', '15', 9),
                                                                        ('aleja Jana Pawła II', '3A', 10),
                                                                        ('aleja Rzeczypospolitej', '1B', 10),
                                                                        ('Żwirki i Wigury', '4/9', 10),
                                                                        ('Konstantego Bergiela', '7', 10),
                                                                        ('Cedrowa', '64', 11),
                                                                        ('ks. Mariana Góreckiego','5',13),
                                                                        ('Dębniki','4',5),
                                                                        ('Morska','5',8),
                                                                        ('Leszczyńskich','1A/6',10),
                                                                        ('Bieszczadzka','19',11),
                                                                        ('Legnicka','41',12),
                                                                        ('Kręckiego','3',4),
                                                                        ('Polanki','51',4),
                                                                        ('Stanisława Wyspiańskiego','9',2),
                                                                        ('Kapliczna','25',8),
                                                                        ('Obrońców Wybrzeża','2',9),
                                                                        ('Aleja Rzeczypospolitej','5',9),
                                                                        ('Subisława','5',9),
                                                                        ('Bolesława Krzywoustego','19B',9),
                                                                        ('Podmłyńska','10',3),
                                                                        ('Podmurze','4',3),
                                                                        ('Pończoszników','3',3),
                                                                        ('Kurza','14/4',3),
                                                                        ('Piastowska','90e',9),
                                                                        ('Obrońców Wybrzeża','1',9),
                                                                        ('Opolska','3',9),
                                                                        ('Biskupa Edmunda Nowickiego','5',4),
                                                                        ('aleja Jana Pawła II','3b',10),
                                                                        ('Kombatantów','5',10),
                                                                        ('aleja Jana Pawła II','48',10),
                                                                        ('aleja Jana Pawła II','3',10),
                                                                        ('Startowa','4A',10),
                                                                        ('Brzozowa','15a',2);


INSERT INTO organisation ("name", description, email, phone_num, address_id, is_approved, logo_url) VALUES
                                                                                                                      ('Fundacja Pomocy Bezdomnym "Troska"', 'Działa na rzecz osób bezdomnych, zapewniając schronienie, posiłki i pomoc psychologiczną.', 'info@troska-fundacja.pl', '654321987', 4, true, 'https://s3.amazonaws.com/www-inside-design/uploads/2019/05/woolmarkimagelogo-1024x576.png'),
                                                                                                                      ('Stowarzyszenie Ochrony Środowiska "Zielone Płuca"', 'Realizuje projekty na rzecz ochrony środowiska, propaguje zrównoważony rozwój.', 'info@zielone-pluca.org', '789123456', 5, true, 'https://activfirst.co.uk/wp-content/uploads/logo-example.jpg'),
                                                                                                                      ('Fundacja Ratowania Zwierząt "Bez Klatek"', 'Angażuje się w ochronę zwierząt hodowlanych, wspierając kampanie przeciwko hodowli klatkowej.', 'info@bez-klatek-fundacja.com', '321654987', 6, true, 'https://icccc.cz/wp-content/uploads/2021/01/logo-example.jpg'),
                                                                                                                      ('Organizacja Pomocy Dzieciom "Aniołki Dobra"', 'Pomaga dzieciom w trudnej sytuacji życiowej, zapewniając wsparcie materialne i edukacyjne.', 'info@aniolki-dobra.org', '456123789', 7, true, 'https://vme-stiftung.de/wp-content/uploads/2019/09/example-logo-2.jpg'),
                                                                                                                      ('Stowarzyszenie Seniorów "Złote Lata"', 'Organizuje programy wsparcia dla seniorów, zapewniając im aktywność społeczną i opiekę.', 'info@zlote-lata-seniorzy.pl', '987654321', 8, true, 'https://thumbs.dreamstime.com/b/demo-icon-demo-147077326.jpg'),
                                                                                                                      ('Fundacja na Rzecz Osób Niepełnosprawnych "Tęcza Nadziei"', 'Świadczy wsparcie i pomoc osobom niepełnosprawnym, dążąc do poprawy ich jakości życia.', 'info@teczanadziei.org', '123789456', 9, true, 'https://cdn3.f-cdn.com//files/download/144571748/professional%20logo.jpg'),
                                                                                                                      ('Klub Wolontariuszy "Daj Czas"', 'Zrzesza wolontariuszy i organizuje akcje charytatywne na rzecz lokalnej społeczności.', 'info@daj-czas.org', '654987321', 10, true, 'https://fiverr-res.cloudinary.com/images/t_main1,q_auto,f_auto,q_auto,f_auto/gigs/302449722/original/f8e24234fe7bd5755c16ca2bfd0ea99419e09a84/make-a-logo-without-revision-limits.png'),
                                                                                                                      ('Fundacja Pomocy Psychologicznej "Zawsze Wsparcie"', 'Oferuje profesjonalne wsparcie psychologiczne dla osób w kryzysie emocjonalnym.', 'info@zawsze-wsparcie-fundacja.pl', '789456123', 11, true, 'https://www.creativefabrica.com/wp-content/uploads/2021/03/10/A-Letter-Logo-Modern-Logo-Design-Graphics-9428003-1-580x435.jpg'),
                                                                                                                      ('Stowarzyszenie Walki z Narkomanią "Wolność Sobie"', 'Prowadzi działania profilaktyczne i terapeutyczne w obszarze uzależnień.', 'info@wolnosc-sobie.org', '321456789', 12, true, 'https://i.pinimg.com/474x/5f/8e/bf/5f8ebf3454338d0390e379539c158384.jpg'),
                                                                                                                      ('Fundacja Edukacyjna dla Dzieci "Akademia Marzeń"', 'Wspiera edukację dzieci z mniejszych miejscowości, zapewniając dostęp do dodatkowych zajęć.', 'info@akademia-marzen.edu', '456789321', 13, true, 'https://t3.ftcdn.net/jpg/03/45/93/66/360_F_345936640_DuPhNnhROHiZTpUcJAjuk8dRNuJmTemX.jpg'),
                                                                                                                      ('Stowarzyszenie Kultury Lokalnej "Kolorowy Świat"', 'Organizuje wydarzenia kulturalne, festiwale i warsztaty dla lokalnej społeczności.', 'info@kolorowy-swiat.org', '987321456', 14, true, 'https://www.logolounge.com/wd/uploads/21910_321325.jpg'),
                                                                                                                      ('Fundacja Sportowa "Aktywni Razem"', 'Promuje aktywność fizyczną wśród dzieci i młodzieży, organizując zajęcia sportowe.', 'info@aktywni-razem.org', '123789321', 15, true, 'https://www.onlinelogomaker.com/blog/wp-content/uploads/2017/07/door-company-logo.jpg'),
                                                                                                                      ('Stowarzyszenie Przyjaciół Zwierząt "Serce dla Puchatka"', 'Działa na rzecz ochrony zwierząt domowych, organizując adopcje i akcje edukacyjne.', 'info@serce-dla-puchatka.org', '456321789', 16, true, 'https://www.creativefabrica.com/wp-content/uploads/2022/05/18/Unique-and-Modern-S-Logo-Design-Graphics-30778385-2-580x387.jpg'),
                                                                                                                      ('Fundacja Pomocy Chorym "Nadzieja Zdrowia"', 'Zbiera fundusze na leczenie chorych osób, organizuje akcje charytatywne.', 'info@nadzieja-zdrowia.org', '789321456', 17, true, 'https://fiverr-res.cloudinary.com/t_profile_original,q_auto,f_auto/attachments/profile/photo/27b8dd26b7c4789d6c623eb905d25c21-1612373830838/2effc771-4df1-42dd-92b0-796e257c318e.jpg');

INSERT INTO event ( name, description, is_pesel_ver_req, is_agreement_needed, organisation_id, image_url, is_approved) VALUES
                                                                                                                                                         ('Dzień Dobra na Ulicach Miasta',
                                                                                                                                                          'Czy chciałbyś/aś dołączyć do nas, aby sprawić, że ulice naszego miasta staną się lepszym miejscem? Razem możemy pomóc osobom bezdomnym, oferując ciepłe posiłki, ubrania i wsparcie psychologiczne. Twoja dobra wola jest mile widziana!',
                                                                                                                                                          true, true, 1, '[url]', true),
                                                                                                                                                         ('Muzyka dla Ludzi Bez Domu: Benefis Charytatywny',
                                                                                                                                                          'Przyłącz się do nas jako wolontariusz podczas charytatywnego koncertu, na którym muzyka łączy się z pomocą potrzebującym. Twoja pomoc w organizacji tego wyjątkowego wydarzenia wpłynie na poprawę życia osób bezdomnych.',
                                                                                                                                                          true, true, 1, '[url]', true),
                                                                                                                                                         ('Zawodowy Rozwój: Droga do Nowego Początku',
                                                                                                                                                          'W chłodne noce potrzebujemy Twojej pomocy jako wolontariusza. Przyłącz się do nas podczas nocnych dyżurów, by razem oferować ciepłe posiłki i schronienie osobom bezdomnym.',
                                                                                                                                                          true, true, 1, '[url]', true),
                                                                                                                                                         ('Ciepła Noc: Nocne Dyżury z Fundacją "Troska"',
                                                                                                                                                          'W chłodne noce potrzebujemy Twojej pomocy jako wolontariusza. Przyłącz się do nas podczas nocnych dyżurów, by razem oferować ciepłe posiłki i schronienie osobom bezdomnym.',
                                                                                                                                                          true, true, 1, '[url]', true),
                                                                                                                                                         ('Kiermasz Dobroczynności "Troska": Tworzymy Nadzieję',
                                                                                                                                                          'Jeśli chciałbyś/aś pomóc w organizacji kiermaszu dobroczynności, towarzysząc nam na tej wspólnej misji, zapraszamy serdecznie! Twoja obecność tworzy nadzieję i radość dla innych.',
                                                                                                                                                          true, true, 1, '[url]', true),
                                                                                                                                                         ('Czyste Plaże: Sprzątanie Wybrzeża z Nami!',
                                                                                                                                                          'Dołącz do nas w akcji sprzątania wybrzeża i pomóż chronić nasze piękne plaże! Niezależnie od doświadczenia, każdy jest mile widziany. Razem możemy zrobić wiele dla naszej przyrody. Dołącz do nas już dziś!',
                                                                                                                                                          true, true, 2, '[url]', true),
                                                                                                                                                         ('Sadzenie Drzew: Zróbmy Coś Dobre dla Natury',
                                                                                                                                                          'Przyłącz się do nas, aby razem sadzić drzewa i dbać o naszą planetę. Nie wymagamy wcześniejszego doświadczenia w sadzeniu drzew, wszyscy chętni są mile widziani! Razem tworzymy lepszą przyszłość dla środowiska.',
                                                                                                                                                          true, false, 2, '[url]', true),
                                                                                                                                                         ('Szkolenie w zakresie Recyklingu i Gospodarki Odpadami',
                                                                                                                                                          'Szukamy wolontariuszy, którzy chcieliby pomóc nam w przeprowadzeniu szkolenia dotyczącego recyklingu i gospodarki odpadami. Twoja pomoc pomoże innym zrozumieć, jak ważne jest właściwe zarządzanie odpadami dla zrównoważonego rozwoju.',
                                                                                                                                                          true, true, 2, '[url]', true),
                                                                                                                                                         ('Wycieczka Ekologiczna do Parku Narodowego',
                                                                                                                                                          'Poszukujemy przewodników i pomocników do organizacji ekologicznej wycieczki do Parku Narodowego. To doskonała okazja, aby dzielić się swoją wiedzą na temat przyrody i wspierać jej ochronę poprzez edukację i świadomość.',
                                                                                                                                                          true, true, 2, '[url]', true),
                                                                                                                                                         ('Aktywizacja Młodzieży na Rzecz Zrównoważonego Rozwoju',
                                                                                                                                                          'Zapraszamy do udziału w naszym projekcie edukacyjnym, którego celem jest aktywizacja młodzieży w działaniach na rzecz zrównoważonego rozwoju. Wspólnie będziemy uczyć młodych ludzi o ochronie środowiska i inspirować ich do podejmowania działań na rzecz naszej planety. Dołącz do nas, aby tworzyć lepszą przyszłość!',
                                                                                                                                                          true, true, 2, '[url]', true),
                                                                                                                                                         ('Akcja Ratowania Zwierząt z Ferm Klatkowych',
                                                                                                                                                          'Szukamy zaangażowanych wolontariuszy, którzy chcieliby nam pomóc w ratowaniu zwierząt z ferm klatkowych. Twoja pomoc może zmienić życie setek zwierząt, które cierpią w tych warunkach.',
                                                                                                                                                          true, true, 3, '[url]', true),
                                                                                                                                                         ('Kampania na Rzecz Zakazu Hodowli Klatkowej',
                                                                                                                                                          'Poszukujemy wolontariuszy, którzy chcieliby się zaangażować w działania lobbingowe, zbieranie podpisów i promowanie świadomości na temat tego problemu społecznego. Razem możemy przyczynić się do wprowadzenia pozytywnych zmian dla zwierząt hodowlanych.',
                                                                                                                                                          true, true, 3, '[url]', true),
                                                                                                                                                         ('Wizyta w Schronisku dla Zwierząt',
                                                                                                                                                          'Serdecznie zapraszamy do udziału w naszym wolontariacie w schronisku dla zwierząt. Jeśli kochasz zwierzęta i chcesz pomóc im poprzez opiekę i pomoc w adopcjach, to ta oferta jest dla Ciebie!',
                                                                                                                                                          true, true, 3, '[url]', true),
                                                                                                                                                         ('Edukacja na Rzecz Praw Zwierząt',
                                                                                                                                                          'Poszukujemy wolontariuszy do pomocy w organizacji wykładów, warsztatów i kampanii edukacyjnych. Twoja praca pomoże rozpowszechnić ideę szacunku i troski o zwierzęta w społeczeństwie.',
                                                                                                                                                          true, true, 3, '[url]', true),
                                                                                                                                                         ('Akcja Pomocy Zwierzętom na Wypadek Katastrof',
                                                                                                                                                          'W ramach naszego programu pomocy zwierzętom w przypadku katastrof poszukujemy wolontariuszy gotowych do działania w sytuacjach awaryjnych. Bierzemy udział w akcjach ratunkowych, pomagając zwierzętom w trudnych sytuacjach, takich jak pożary czy powodzie. Jeśli masz umiejętności i chęci, aby pomagać w ekstremalnych warunkach, dołącz do naszego zespołu ratunkowego. Twoja praca może ocalić życie wielu zwierząt.',
                                                                                                                                                          true, true, 3, '[url]', true),
                                                                                                                                                         ('Święta dla Dzieci w Potrzebie',
                                                                                                                                                          'Zapraszamy serdecznych wolontariuszy, aby dołączyli do naszej rodziny Aniołków Dobra podczas zbliżających się Świąt Bożego Narodzenia. Przygotowujemy wyjątkowe święta dla dzieci, które znalazły się w trudnych sytuacjach życiowych. Wspólnie możemy sprawić, że te dni będą pełne ciepła, miłości i uśmiechu.',
                                                                                                                                                          true, true, 4, '[url]', true),
                                                                                                                                                         ('Wspólna Praca nad Przyszłością Młodzieży',
                                                                                                                                                          'Nasza misja polega na wsparciu młodzieży w pokonywaniu trudności życiowych i budowaniu własnej przyszłości. Szukamy pasjonatów, którzy chcieliby być mentorami i przyjaciółmi młodym ludziom w potrzebie. Twoja obecność i wsparcie mogą pomóc w kształtowaniu ich marzeń i perspektyw.',
                                                                                                                                                          true, true, 4, '[url]', true),
                                                                                                                                                         ('Letnia Przygoda z Dziećmi w Trudnej Sytuacji',
                                                                                                                                                          'Przygotowujemy letni obóz dla dzieci, które nie miły okazji na wakacyjne przygody. Poszukujemy wolontariuszy, którzy chcieliby spędzić czas na obozie, organizując zajęcia, pełniąc rolę przewodników i tworząc niezapomniane wspomnienia. Twoja obecność może sprawić, że te letnie dni staną się niezapomnianym doświadczeniem.',
                                                                                                                                                          true, true, 4, '[url]', true),
                                                                                                                                                         ('Wsparcie Edukacyjne dla Młodych Talentów',
                                                                                                                                                          'Nasza organizacja angażuje się w dostarczanie wsparcia edukacyjnego dla dzieci i młodzieży w trudnej sytuacji. Szukamy wolontariuszy, którzy mogą pomagać w nauczaniu, udzielaniu korepetycji i rozwijaniu umiejętności uczniów. Twoja pomoc może być kluczem do ich sukcesu edukacyjnego.',
                                                                                                                                                          true, true, 4, '[url]', true),
                                                                                                                                                         ('Wspieranie Rodzin w Trudnym Położeniu',
                                                                                                                                                          'Poszukujemy wolontariuszy, którzy chcieliby pomóc w aktywizacji rodzin z dziećmi w trudnej sytuacji życiowej. Możesz udzielać wsparcia psychologicznego, organizować warsztaty i pomagać w rozwiązywaniu codziennych problemów. Twoja praca może być iskrą, która pomaga tym rodzinom znaleźć lepszą drogę do przodu.',
                                                                                                                                                          true, true, 4, '[url]', true),
                                                                                                                                                         ('Seniorzy Aktywnie - Zajęcia Rekreacyjne',
                                                                                                                                                          'Serdecznie zapraszamy do dołączenia do naszego programu "Seniorzy Aktywnie", gdzie nasi cenni seniorzy mogą cieszyć się aktywnością rekreacyjną i towarzyską. Szukamy życzliwych wolontariuszy, którzy chcieliby pomagać w organizacji zajęć, gier planszowych, spacerów i rozmów. Twoja obecność sprawi, że te "Złote Lata" będą jeszcze piękniejsze.',
                                                                                                                                                          true, true, 5, '[url]', true),
                                                                                                                                                         ('Wsparcie Seniorów w Codziennych Obowiązkach',
                                                                                                                                                          'Nasza organizacja poszukuje serdecznych wolontariuszy, którzy mogą pomóc naszym seniorom w codziennych obowiązkach, takich jak zakupy spożywcze, wizyty u lekarza czy prace domowe. Twoja pomoc będzie oznaczać wiele dla naszych podopiecznych i pozwoli im cieszyć się niezależnością.',
                                                                                                                                                          true, true, 5, '[url]', true),
                                                                                                                                                         ('Warsztaty Kulturalne i Twórcze dla Seniorów',
                                                                                                                                                          'Zapraszamy do udziału w naszych warsztatach kulturalnych i twórczych dla seniorów. Szukamy wolontariuszy, którzy chcieliby dzielić się swoimi umiejętnościami i pasją z naszymi seniorami. Razem możemy odkryć nowe talenty i rozwijać kreatywność wśród naszych "Złotych Lat".',
                                                                                                                                                          true, true, 5, '[url]', true),
                                                                                                                                                         ('Klub Czytelniczy dla Seniorów',
                                                                                                                                                          'Nasz klub czytelniczy dla seniorów to miejsce, gdzie nasi starsi przyjaciele mogą dzielić się swoją miłością do książek i literatury. Poszukujemy wolontariuszy, którzy chcieliby prowadzić dyskusje, organizować spotkania autorskie i udzielać wsparcia przy czytaniu. Twoja pasja do literatury może stać się inspiracją dla naszych seniorów.',
                                                                                                                                                          true, true, 5, '[url]', true),
                                                                                                                                                         ('Złote Lata - Wyjazdy i Rejsy',
                                                                                                                                                          'Nasze "Złote Lata" zasługują na wyjątkowe przygody i wspomnienia. Szukamy wolontariuszy, którzy chcieliby pomóc w organizacji wyjazdów i rejsów dla naszych seniorów. Twój udział pozwoli im odkrywać nowe miejsca i cieszyć się życiem w pełni, nawet w późniejszych latach.',
                                                                                                                                                          true, true, 5, '[url]', true),
                                                                                                                                                         ('Dzień Marzeń Dla Osób Niepełnosprawnych',
                                                                                                                                                          'Serdecznie zapraszamy wolontariuszy do udziału w naszym wydarzeniu "Dzień Marzeń", gdzie chcemy spełniać życzenia osób niepełnosprawnych. Szukamy marzycieli i organizatorów, którzy pomogą w realizacji tych wyjątkowych chwil. Twoje zaangażowanie może uczynić ich marzenia rzeczywistością.',
                                                                                                                                                          true, true, 6, '[url]', true),
                                                                                                                                                         ('Wsparcie w Terapii i Rehabilitacji',
                                                                                                                                                          'Nasza organizacja oferuje terapie i rehabilitację osobom niepełnosprawnym, pomagając im poprawić jakość życia. Szukamy wolontariuszy, którzy chcieliby asystować podczas terapii, udzielać wsparcia emocjonalnego i pomagać w rehabilitacji. Twoja obecność może być kluczem do ich sukcesu i samodzielności.',
                                                                                                                                                          true, true, 6, '[url]', true),
                                                                                                                                                         ('Wsparcie w Terapii i Rehabilitacji',
                                                                                                                                                          'Nasza organizacja oferuje terapie i rehabilitację osobom niepełnosprawnym, pomagając im poprawić jakość życia. Szukamy wolontariuszy, którzy chcieliby asystować podczas terapii, udzielać wsparcia emocjonalnego i pomagać w rehabilitacji. Twoja obecność może być kluczem do ich sukcesu i samodzielności.',
                                                                                                                                                          true, true, 6, '[url]', true),
                                                                                                                                                         ('Klub Kulturalny Osób Niepełnosprawnych',
                                                                                                                                                          'Nasz Klub Kulturalny to miejsce, gdzie osoby niepełnosprawne mogą cieszyć się sztuką i kulturą. Poszukujemy wolontariuszy, którzy chcieliby organizować wydarzenia kulturalne, warsztaty artystyczne i wspierać naszych członków w rozwijaniu swoich pasji. Twoja kreatywność może rozjaśnić życie naszych podopiecznych.',
                                                                                                                                                          true, true, 6, '[url]', true),
                                                                                                                                                         ('Wsparcie Rodzin Osób Niepełnosprawnych',
                                                                                                                                                          'Nasza fundacja działa również na rzecz rodzin osób niepełnosprawnych. Poszukujemy wolontariuszy, którzy chcieliby oferować wsparcie emocjonalne i praktyczne dla rodzin w potrzebie. Twoja obecność może pomóc im w radzeniu sobie z wyzwaniami codziennego życia.',
                                                                                                                                                          true, true, 6, '[url]', true),
                                                                                                                                                         ('Sprzątanie Parku - Razem dla Czystości',
                                                                                                                                                          'Poszukujemy aktywnych wolontariuszy do udziału w akcji sprzątania parku. Razem możemy uczynić naszą lokalną społeczność czystszą i bardziej przyjazną dla wszystkich. Dołącz do nas i pomóż nam dawać czas na rzecz piękniejszego otoczenia!',
                                                                                                                                                          true, true, 7, '[url]', true),
                                                                                                                                                         ('Pomoc Dla Bezdomnych',
                                                                                                                                                          'Organizujemy akcję wsparcia dla bezdomnych mieszkańców naszej okolicy. Szukamy wolontariuszy, którzy chcieliby dostarczać posiłki, odzież i rozmawiać z osobami potrzebującymi wsparcia. Twoja pomoc może pomóc tym, którzy najbardziej jej potrzebują.',
                                                                                                                                                          true, true, 7, '[url]', true),
                                                                                                                                                         ('Klub Seniora - Tworzymy Wspólnotę',
                                                                                                                                                          'Tworzymy Klub Seniora, w którym nasi starsi sąsiedzi mogą spędzać czas razem i dzielić się swoimi historiami. Poszukujemy wolontariuszy, którzy chcieliby pomagać w organizacji spotkań, imprez towarzyskich i opiekować się naszymi starszymi przyjaciółmi. Twoja obecność może stworzyć ciepłą i przyjazną wspólnotę.',
                                                                                                                                                          true, true, 7, '[url]', true),
                                                                                                                                                         ('Pomoc Dla Dzieci w Potrzebie - Wspólna Troska',
                                                                                                                                                          'Nasza akcja charytatywna skupia się na pomocy dzieciom w trudnej sytuacji życiowej. Szukamy wolontariuszy, którzy chcieliby zbierać artykuły szkolne, zabawki i odzież dla dzieci. Twoja troska może uczynić życie młodych mieszkańców naszej okolicy lepszym.',
                                                                                                                                                          true, true, 7, '[url]', true),
                                                                                                                                                         ('Aktywizacja Społeczna - Razem Wspieramy',
                                                                                                                                                          'Nasz klub promuje aktywne zaangażowanie w społeczności. Poszukujemy wolontariuszy, którzy chcieliby organizować wydarzenia społeczne, warsztaty edukacyjne i akcje dobroczynne. Razem możemy działać na rzecz lokalnej społeczności i tworzyć pozytywne zmiany. Dołącz do nas, aby razem dawać czas na rzecz innych!',
                                                                                                                                                          true, true, 7, '[url]', true),
                                                                                                                                                         ('Linia Wsparcia Dla Osób w Kryzysie',
                                                                                                                                                          'Poszukujemy wolontariuszy do naszej linii wsparcia dla osób w kryzysie emocjonalnym. Jeśli masz empatię i słuchasz uważnie, dołącz do nas, aby pomóc tym, którzy potrzebują wsparcia psychologicznego. Twoje wsparcie może być kluczem do poprawy życia innych.',
                                                                                                                                                          true, true, 8, '[url]', true),
                                                                                                                                                         ('Wsparcie Grupowe - Razem Przezwyciężamy Kryzys',
                                                                                                                                                          'Nasza fundacja organizuje sesje wsparcia grupowego dla osób borykających się z problemami emocjonalnymi. Szukamy wolontariuszy, którzy chcieliby prowadzić te sesje, dostarczać wsparcie emocjonalne i pomagać w budowaniu zdrowych relacji. Twoje umiejętności mogą pomóc w przezwyciężeniu trudności.',
                                                                                                                                                          true, true, 8, '[url]', true),
                                                                                                                                                         ('Warsztaty Samopomocy i Rozwoju Osobistego',
                                                                                                                                                          'Nasze warsztaty samopomocy i rozwoju osobistego to szansa dla osób w kryzysie na rozwijanie swoich umiejętności i odnalezienie wewnętrznego równowagi. Szukamy wolontariuszy, którzy chcieliby prowadzić te warsztaty i dzielić się wiedzą z innymi. Twoja pomoc może być kluczem do ich wzrostu i rozwoju.',
                                                                                                                                                          true, true, 8, '[url]', true),
                                                                                                                                                         ('Wsparcie Dla Rodzin w Kryzysie',
                                                                                                                                                          'Nasza fundacja oferuje wsparcie psychologiczne dla rodzin dotkniętych kryzysem emocjonalnym. Szukamy wolontariuszy, którzy chcieliby asystować psychoterapeutom podczas sesji terapeutycznych, udzielać wsparcia rodzicom i dzieciom oraz pomagać w budowaniu zdrowych relacji rodzinnych. Twoja obecność może przynieść ulgę i nadzieję tym rodzinom.',
                                                                                                                                                          true, true, 8, '[url]', true),
                                                                                                                                                         ('Dni Otwarte - Poznaj Naszą Pracę',
                                                                                                                                                          'Chcielibyśmy zaprosić wolontariuszy do udziału w naszych Dniach Otwartych, gdzie mogą poznać naszą pracę i misję. Szukamy osób, które pomogą w organizacji wydarzeń, udzielaniu informacji oraz tworzeniu otwartego i przyjaznego środowiska. Twoja obecność może pomóc w promowaniu zdrowia psychicznego w społeczności.',
                                                                                                                                                          true, true, 8, '[url]', true),
                                                                                                                                                         ('Wsparcie w Działaniach Antyuzależnieniowych',
                                                                                                                                                          'Poszukujemy zaangażowanych wolontariuszy, którzy chcieliby dołączyć do naszych działań antyuzależnieniowych. Razem możemy prowadzić działania profilaktyczne, edukacyjne i terapeutyczne, aby pomóc osobom borykającym się z uzależnieniami od różnych substancji i zachowań. Dołącz do nas, aby razem walczyć o zdrową i wolną od uzależnień społeczność.',
                                                                                                                                                          true, true, 9, '[url]', true),
                                                                                                                                                         ('Terapeutyczne Warsztaty - Razem Przezwyciężamy Uzależnienia',
                                                                                                                                                          'Nasze stowarzyszenie organizuje terapeutyczne warsztaty dla osób walczących z różnymi rodzajami uzależnień, takimi jak uzależnienie od komputera czy alkoholu. Szukamy wolontariuszy, którzy chcieliby prowadzić te warsztaty, dostarczać wsparcie emocjonalne i wspierać proces zdrowienia. Twoje zaangażowanie może być kluczem do odzyskania kontroli nad swoim życiem.',
                                                                                                                                                          true, true, 9, '[url]', true),
                                                                                                                                                         ('Kampania Przeciwna Uzależnieniom - Edukacja i Świadomość',
                                                                                                                                                          'Przygotowujemy kampanię przeciwną uzależnieniom, która ma na celu zwiększenie świadomości na temat różnych rodzajów uzależnień. Poszukujemy wolontariuszy, którzy chcieliby pomóc w organizacji wydarzeń, spotkań edukacyjnych i działań społecznych. Twoja praca może pomóc w zapobieganiu uzależnieniom od różnych źródeł.',
                                                                                                                                                          true, true, 9, '[url]', true),
                                                                                                                                                         ('Wsparcie Rodzin - Łączymy i Pomagamy',
                                                                                                                                                          'Nasze stowarzyszenie oferuje wsparcie rodzinom dotkniętym uzależnieniami od różnych substancji i zachowań. Szukamy wolontariuszy, którzy chcieliby pomagać w organizacji spotkań wsparcia, udzielać rad rodzicom i kreować bezpieczne przestrzenie do rozmów. Twoja obecność może pomóc rodzinom w trudnym czasie.',
                                                                                                                                                          true, true, 9, '[url]', true);
INSERT INTO address_to_event ( event_id, address_id) VALUES
                                                         ( 4, 4),
                                                         ( 5, 5),
                                                         ( 6, 6),
                                                         ( 7, 7),
                                                         ( 8, 8),
                                                         ( 9, 9),
                                                         (10,10),
                                                         (11,11),
                                                         (12,12),
                                                         (13,13),
                                                         (14,14),
                                                         (15,15),
                                                         (16,16),
                                                         (17,17),
                                                         (18,18),
                                                         (19,19),
                                                         (20,20),
                                                         (21,21),
                                                         (22,22),
                                                         (23,23),
                                                         (24,24),
                                                         (25,25),
                                                         (26,26),
                                                         (27,27),
                                                         (28,28),
                                                         (29,29),
                                                         (30,30),
                                                         (31,31),
                                                         (32,32),
                                                         (33,33),
                                                         (34,34),
                                                         (35,35),
                                                         (36,36),
                                                         (37,37),
                                                         (38,38),
                                                         (39,39),
                                                         (40,40),
                                                         (41,41),
                                                         (42,42),
                                                         (43,43),
                                                         (44,44),
                                                         (45,45),
                                                         (46,46),
                                                         (47,47);
INSERT INTO shift ( address_to_event_id, start_time, end_time, date, capacity, is_leader_required, required_min_age, directions) VALUES
                                                                                                                            (4, '08:00:00', '11:00:00', '2023-06-17', 25, false, 12, 'Manhattan Gdańskie Centrum Handlowe'),
                                                                                                                            (5, '13:30:00', '16:30:00', '2023-06-20', 18, false, 16, 'Gdańska Spółdzielnia Socjalna, na domofonie 11'),
                                                                                                                            (6, '09:45:00', '12:45:00', '2023-06-22', 12, false, 18, 'w trakcie roku szkolnego w godzinach 12:00-17:00'),
                                                                                                                            (7, '15:00:00', '18:00:00', '2023-06-25', 30, false, 12, ''),
                                                                                                                            (8, '11:30:00', '14:30:00', '2023-06-28', 22, false, 16, 'w trakcie roku szkolnego w godzinach 12:00-17:00'),
                                                                                                                            (9, '08:15:00', '11:15:00', '2023-07-01', 15, false, 18, ''),
                                                                                                                            (10, '14:45:00', '17:45:00', '2023-07-04', 20, false, 12, 'wejście przez przychodnie weterynaryjną'),
                                                                                                                            (11, '10:00:00', '13:00:00', '2023-07-07', 25, false, 16, ''),
                                                                                                                            (12, '16:30:00', '19:30:00', '2023-07-10', 18, false, 18, 'W budynku parafii Matki Bożej Częstochowskiej'),
                                                                                                                            (13, '09:30:00', '12:30:00', '2023-07-13', 12, false, 12, ''),
                                                                                                                            (14, '15:15:00', '18:15:00', '2023-07-16', 28, false, 16, ''),
                                                                                                                            (15, '11:45:00', '14:45:00', '2023-07-19', 20, false, 18, ''),
                                                                                                                            (16, '08:45:00', '11:45:00', '2023-07-22', 15, false, 12, ''),
                                                                                                                            (17, '14:15:00', '17:15:00', '2023-07-25', 25, false, 16, 'wejście przez zieloną bramę'),
                                                                                                                            (18, '10:30:00', '13:30:00', '2023-07-28', 18, false, 18, ''),
                                                                                                                            (19, '16:00:00', '19:00:00', '2023-07-31', 22, false, 12, 'Na drugim piętrze, Dzwonić pod 6'),
                                                                                                                            (20, '09:00:00', '12:00:00', '2023-08-03', 30, false, 16, 'Naprzeciwko Ośrodka Szkolno - Wychowawczego nr 2'),
                                                                                                                            (21, '14:30:00', '17:30:00', '2023-08-06', 12, false, 18, 'Wojewódzka Stacja Sanitarno - Epidemiologiczna w Gdańsku'),
                                                                                                                            (22, '10:15:00', '13:15:00', '2023-08-09', 18, false, 12, 'Willa Morskie oko'),
                                                                                                                            (23, '15:45:00', '18:45:00', '2023-08-12', 25, false, 16, ' Na drugim piętrze, Dzwonić pod 6'),
                                                                                                                            (24, '11:00:00', '14:00:00', '2023-08-15', 20, false, 18, 'Pizzeria Papryczka'),
                                                                                                                            (25, '16:15:00', '19:15:00', '2023-08-18', 15, false, 12, 'Warsztat Samochodowy'),
                                                                                                                            (26, '09:45:00', '12:45:00', '2023-08-21', 28, false, 16, 'Niedaleko GAUM Gdańskiej Akademii Umiejętności Menedżerskich'),
                                                                                                                            (27, '15:30:00', '18:30:00', '2023-08-24', 22, false, 18, 'Centrum Informacji i Edukacji Ekologicznej'),
                                                                                                                            (28, '10:30:00', '13:30:00', '2023-08-27', 18, false, 12, 'Zarząd Transportu Miejskiego. Punkt obsługi klienta'),
                                                                                                                            (29, '16:00:00', '19:00:00', '2023-08-30', 25, false, 16, 'Bambini 3. Przedszkole Montessori'),
                                                                                                                            (30, '08:45:00', '11:45:00', '2023-09-02', 20, false, 18, 'Filia Naukowa (Filia WiMBP)'),
                                                                                                                            (31, '14:15:00', '17:15:00', '2023-09-05', 15, false, 12, 'Przedszkole nr 62 "Kraina Bajek"'),
                                                                                                                            (32, '10:00:00', '13:00:00', '2023-09-08', 22, false, 16, 'GDDKiA Oddział w Gdańsku'),
                                                                                                                            (33, '15:30:00', '18:30:00', '2023-09-11', 25, false, 18, 'Osiedle Oliwa Park'),
                                                                                                                            (34, '11:45:00', '14:45:00', '2023-09-14', 28, false, 12, 'Akademia Coś tam wymyślę'),
                                                                                                                            (35, '16:15:00', '19:15:00', '2023-09-17', 18, false, 16, 'Obok Wypożyczalni rowerów'),
                                                                                                                            (36, '09:30:00', '12:30:00', '2023-09-20', 20, false, 18, 'Wypożyczalnia Rowerów "Bike Rental Gdańsk"'),
                                                                                                                            (37, '15:00:00', '18:00:00', '2023-09-23', 25, false, 12, 'W Odnowionej kamienicy TBS Motława na 3 piętrze'),
                                                                                                                            (38, '10:45:00', '13:45:00', '2023-09-26', 15, false, 16, 'Poczta Polska'),
                                                                                                                            (39, '16:30:00', '19:30:00', '2023-09-29', 22, false, 18, 'Centrum handlowe "Galeria Przymorze"'),
                                                                                                                            (40, '11:15:00', '14:15:00', '2023-10-02', 28, false, 12, 'Biblioteka Babie Lato (Filia WiMBP)'),
                                                                                                                            (41, '15:45:00', '18:45:00', '2023-10-05', 18, false, 16, 'Katedra Oliwska'),
                                                                                                                            (42, '10:30:00', '13:30:00', '2023-10-08', 25, false, 18, 'Laboratoria Medyczne Bruss Grupa Alab Sp. z o.o.'),
                                                                                                                            (43, '16:00:00', '19:00:00', '2023-10-11', 20, false, 12, 'Medicus Agencja usług opiekuńczo - pielęgniarskich'),
                                                                                                                            (44, '09:45:00', '12:45:00', '2023-10-14', 15, false, 16, 'Parafia Opatrzności Bożej w Gdańsku'),
                                                                                                                            (45, '15:15:00', '18:15:00', '2023-10-17', 22, false, 18, 'Niedaleko przystanku Rzeczypospolitej 02'),
                                                                                                                            (46, '11:00:00', '14:00:00', '2023-10-20', 25, false, 12, 'QuestRooms, obok stacji ładowania ORLEN'),
                                                                                                                            (47, '16:30:00', '19:30:00', '2023-10-23', 18, false, 16, 'Naprzeciwko Salonu optycznego');
INSERT INTO category_to_event (category_id, event_id) VALUES
                                                          (4, 1),
                                                          (5, 2),
                                                          (6, 3),
                                                          (1, 4),
                                                          (2, 5),
                                                          (3, 6),
                                                          (4, 7),
                                                          (5, 8),
                                                          (6, 9),
                                                          (1, 10),
                                                          (2, 11),
                                                          (3, 12),
                                                          (4, 13),
                                                          (5, 14),
                                                          (6, 15),
                                                          (1, 16),
                                                          (2, 17),
                                                          (3, 18),
                                                          (4, 19),
                                                          (5, 20),
                                                          (6, 21),
                                                          (1, 22),
                                                          (2, 23),
                                                          (3, 24),
                                                          (4, 25),
                                                          (5, 26),
                                                          (6, 27),
                                                          (1, 28),
                                                          (2, 29),
                                                          (3, 30),
                                                          (4, 31),
                                                          (5, 32),
                                                          (6, 33),
                                                          (1, 34),
                                                          (2, 35),
                                                          (3, 36),
                                                          (4, 37),
                                                          (5, 38),
                                                          (6, 39),
                                                          (1, 40),
                                                          (2, 41),
                                                          (3, 42),
                                                          (4, 43),
                                                          (5, 44),
                                                          (6, 45),
                                                          (1, 46),
                                                          (2, 47);

INSERT INTO privilege (name) VALUES
                                 ('JOIN_EVENT'),
                                 ('CREATE_EVENT'),
                                 ('EDIT_EVENT'),
                                 ('ADMIN_PANEL');


INSERT INTO privilege_to_role (role_id, privilege_id) VALUES
                                                          (1, 4),
                                                          (1, 3),
                                                          (2, 2),
                                                          (2, 3),
                                                          (3, 1);
