--liquibase formatted sql

--changeset woloapp:023
-- final mockup data

INSERT INTO report (report_pl, report_en, report_ua, report_ru, published, event_id) VALUES
                                                                                         ('Dzięki waszemu wsparciu udało się zorganizować wsparcie dla kilku noclegowni dla bezdomnych, jesteśmy wdzięczni za waszą szczodrą pomoc.',
                                                                                          'Thanks to your support, we managed to organize support for several homeless shelters, we are grateful for your generous help.',
                                                                                          'Завдяки вашій підтримці нам вдалося організувати підтримку кількох притулків для бездомних, ми вдячні за вашу щедру допомогу.',
                                                                                          'Благодаря вашей поддержке нам удалось организовать поддержку для нескольких ночлежек для бездомных, мы благодарны за вашу щедрую помощь.',
                                                                                          TRUE, 1),
                                                                                         ('Koncert uważamy za udane wydarzenie, wszystko poszło jak zakładaliśmy, dziękujemy wszystkim wolontariuszom',
                                                                                          'We consider the concert a successful event, everything went as we planned, thank you to all the volunteers',
                                                                                          'Концерт вважаємо вдалим заходом, все пішло як ми планували, дякуємо всім волонтерам',
                                                                                          'Концерт считаем удачным мероприятием, всё прошло как мы планировали, благодарим всех волонтеров',
                                                                                          FALSE, 2),
                                                                                         ('Zmiany, w których potrzebowaliśmy najwięcej wolontariuszy, odbyły się bez zakłóceń, dziękujemy za zaangażowanie',
                                                                                          'The shifts in which we needed the most volunteers went smoothly, thank you for your commitment',
                                                                                          'Зміни, в яких нам потрібно було найбільше волонтерів, пройшли без перешкод, дякуємо за залучення',
                                                                                          'Смены, в которых нам нужно было больше всего волонтеров, прошли без сбоев, спасибо за участие',
                                                                                          TRUE, 3),
                                                                                         ('Podczas zmian udało nam się zebrać sporo odpadów z plaż, nie wyobrażamy sobie tego bez waszego wsparcia',
                                                                                          'During the shifts, we managed to collect a lot of waste from the beaches, we can''t imagine it without your support',
                                                                                          'Під час змін нам вдалося зібрати багато відходів з пляжів, ми не уявляємо цього без вашої підтримки',
                                                                                          'Во время смен нам удалось собрать много мусора с пляжей, мы не представляем этого без вашей поддержки',
                                                                                          TRUE, 6),
                                                                                         ('Dostaliśmy opinie od osób, które brały w wycieczkach, że wy, wolontariusze, którzy zgłosili się na role przedowników i pracowników w ramach tych wycieczek, wykonaliście świetny kawał roboty, i zachęciliście wycieczkowiczów na więcej. Jesteśmy niezmiernie wdzięczni.',
                                                                                          'We received feedback from people who took part in the trips that you, volunteers who signed up for the roles of leaders and workers within these trips, did a great job and encouraged the participants to more. We are extremely grateful.',
                                                                                          'Ми отримали відгуки від людей, які брали участь у поїздках, що ви, волонтери, які зареєструвалися на ролі провідників та працівників у межах цих поїздок, виконали велику роботу і заохотили учасників до більшого. Ми надзвичайно вдячні.',
                                                                                          'Мы получили отзывы от людей, которые принимали участие в поездках, что вы, волонтеры, которые зарегистрировались на роли проводников и работников в рамках этих поездок, сделали отличную работу и побудили участников к большему. Мы безмерно благодарны.',
                                                                                          FALSE, 9),
                                                                                         ('Z waszą pomocą pomogliśmy zwierzętom znaleźć lepsze warunki do życia, dzięki',
                                                                                          'With your help, we helped animals find better living conditions, thanks',
                                                                                          'З вашою допомогою ми допомогли тваринам знайти кращі умови для життя, дякуємо',
                                                                                          'С вашей помощью мы помогли животным найти лучшие условия для жизни, спасибо',
                                                                                          TRUE, 11),
                                                                                         ('Dziękujemy za pomoc w schronisku tak licznej grupie osób, zwierzęta również są wdzięczne za wasze wsparcie',
                                                                                          'Thank you for helping such a large group of people in the shelter, the animals are also grateful for your support',
                                                                                          'Дякуємо за допомогу в притулку такій великій групі людей, тварини також вдячні за вашу підтримку',
                                                                                          'Спасибо за помощь в приюте такой большой группе людей, животные также благодарны за вашу поддержку',
                                                                                          TRUE, 13),
                                                                                         ('Nasi podopieczni są zadowoleni z waszej pomocy, która pozwoliła im rozwinąć się kulturowo, dziękujemy',
                                                                                          'Our charges are happy with your help, which has allowed them to develop culturally, thank you',
                                                                                          'Наші підопічні задоволені вашою допомогою, яка дозволила їм розвиватися культурно, дякуємо',
                                                                                          'Наши подопечные довольны вашей помощью, которая позволила им развиваться культурно, спасибо',
                                                                                          FALSE, 29);